### ISSUE TITLE
Add functionality for long-text input problem

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#11]
See: [PR 475](https://github.com/open-resources/instructor_physics_bank/pull/475)

**Comment by firasm** [comment]
hey @michaelwkudla - good news! The [Rich-text editor](https://prairielearn.readthedocs.io/en/latest/elements/#pl-rich-text-editor-element) is now merged into PL!

Can you update the template you created in PR #475 to use this one instead ?

![pl-rich-text-editor](https://user-images.githubusercontent.com/2507459/131548888-bdd5bd25-2f6c-4d3f-b036-db7e3dc2add1.png)

**Comment by michaelwkudla** [comment]
I have attempted to implement this here: 
https://ca.prairielearn.org/pl/course/38/question/230840/file_edit/questions/Describe_an_Experiment/question.html

It doesn't seem to work. Do we need to update our version of PL for the course or something? 
MK

**Comment by firasm** [comment]
I think you just need to close the tag:

`<pl-rich-text-editor`

**Comment by michaelwkudla** [comment]
It's closed: 
<pl-rich-text-editor
  file-name="answer.html">
</pl-rich-text-editor>

**Comment by michaelwkudla** [comment]
<pl-rich-text-editor file-name="answer.html">
</pl-rich-text-editor> 
Also doesn't work

**Comment by michaelwkudla** [comment]
Also doesn't work: 
`<pl-rich-text-editor
file-name="answer.html">`
`</pl-rich-text-editor>`

**Comment by firasm** [comment]
Oops!

Hmmm ok it looks like it was merged in to master, but not deployed yet. So hopefully this weekend there will be a new version deployed

**Comment by michaelwkudla** [comment]
Ok. We'll wait and see I suppose.

**Comment by firasm** [comment]
This is now *finally* deployed on PL: 🎉

<img width="1276" alt="Screen Shot 2021-09-16 at 7 41 57 AM" src="https://user-images.githubusercontent.com/2507459/133632829-20eedef2-6424-4b50-8905-873e8b53110a.png">

**Comment by michaelwkudla** [comment]
Great!

**Comment by michaelwkudla** [comment]
I just realized that this issue should still be open. We haven't made the template yet, nor the conversion script modifications.

**Comment by firasm** [comment]
This has been implemented
