### ISSUE TITLE
Cryptic (and incorrect) error message: "Multiple choice question part4 does not have a correct answer"

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#118]
Not sure if this is due to recent changes, or an issue from the past, but after #116 was merged in, the script failed on the [OPB-physics bank](https://github.com/open-resources/problem_bank_scripts/actions/runs/10399892418/job/28799500068).

We will eventually lose the logs and the previous link won't contain the details, so I've captured the relevant details here:

When the script ran after #116, the GitHub Actions run log had this problem:

```
ValueError: Multiple choice question part4 does not have a correct answer and the pl-customization `none-of-the-above` was not set to `correct` or `random`.
```

After fixing this line in the [offending question](https://github.com/open-resources/instructor_physics_bank/blob/main/source/004.Kinematics(1D)/Velocity/Velocity%20of%20a%20ball%20from%20acceleration/velocity_of_ball_from_acc.md):

from "Question Text" (error) to "Part 1" (correct), the script ran successfully - [diff here](https://github.com/open-resources/instructor_physics_bank/commit/8a78655581e6789c64ba469708b158e075add06f#diff-44280d8a565ed54b8568f27415c2e4b151202bf3eedfbf001edb2cb602ef5b42L78).

Clearly this question doesn't have 4 parts, and I don't see why the customization is being reported here.

<details>

```
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Velocity/Position Velocity and Acceleration of particle/position_veloctity_acceleration_of_particle.md
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Velocity/Velocity T-F/Velocity T-F.md
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Velocity/Choose the correct graph/Choose the correct graph.md
Traceback (most recent call last):
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Velocity/Velocity of a ball from acceleration/velocity_of_ball_from_acc.md
  File "/home/runner/.local/lib/python3.10/site-packages/problem_bank_scripts/scripts/process.py", line 86, in _do_run
    process_question_pl(source_filepath)
  File "/home/runner/.local/lib/python3.10/site-packages/problem_bank_scripts/problem_bank_scripts.py", line 920, in process_question_pl
    raise ValueError(msg)
ValueError: Multiple choice question part4 does not have a correct answer and the pl-customization `none-of-the-above` was not set to `correct` or `random`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/bin/process", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.local/lib/python3.10/site-packages/problem_bank_scripts/scripts/process.py", line 116, in main
    return args.func(args, parser)
  File "/home/runner/.local/lib/python3.10/site-packages/problem_bank_scripts/scripts/process.py", line 89, in _do_run
    e.add_note(f"Error in processing question: {source_filepath}")
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Non-Uniform Motion (Constant Acceleration)/Jet Braking/Jet_Braking.md
/home/runner/work/problem_bank_scripts/problem_bank_scripts/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md
AttributeError: 'ValueError' object has no attribute 'add_note'
```
</detail>

**Comment by Bluesy1** [comment]
Unfortunately, I can't access most of those links - I don't have access to the physics bank, so I can't take a look at the question locally

**Comment by firasm** [comment]
Gave you access to instructor physics bank

**Comment by Bluesy1** [comment]
Thanks! - This is actually a bug in the Rocket Dog question: https://ca.prairielearn.com/pl/course/38/question/242591/preview?variant_id=17164808

It has an if-elif condition, with no else branch, leading to the possibility of an invalid variant

**Comment by Bluesy1** [comment]
For example, if https://github.com/open-resources/instructor_physics_bank/blob/8a78655581e6789c64ba469708b158e075add06f/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md?plain=1#L52 generates a `coeff_list` of `[-6, 9, 6]`, and https://github.com/open-resources/instructor_physics_bank/blob/8a78655581e6789c64ba469708b158e075add06f/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md?plain=1#L86 generates a `time` of `2`, we get an `x_time` of 0, which makes both conditions return `False`

**Comment by firasm** [comment]
Ahh - nice! That explains why such a trivial change made it work again. 

Okay, I'll report this to OPBP and try to quickly fix it otherwise I'll forget about it.

**Comment by firasm** [comment]
FYI [Fixed here](https://github.com/open-resources/instructor_physics_bank/commit/fb1aa15193085538a1d1e97bb22269b4720c3235) but completely untested.

**Comment by Bluesy1** [comment]
I think that could still allow `v_time` to be 0, which would cause the same issue, here's a diff that should fix it:
```diff
diff --git a/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md b/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md
index b3faa9b8953..e6fc19e3941 100644
--- a/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md
+++ b/source/004.Kinematics(1D)/Acceleration/Rocket_Dog/Rocket_Dog.md
@@ -81,13 +81,16 @@ server:
 
         # generate the position polynomial
         x = gen_poly(t)
+        v  = sp.diff(x)
 
         # define bounds of the variables
         x_time = 0
+        v_time = 0
         # Add a check to make sure x_time isn't 0, if so, regenerate
-        while x_time == 0:
+        while x_time == 0 or v_time == 0:
             time = rd.randint(2,10)
             x_time = x.subs(t, time)
+            v_time = v.subs(t, time)
 
 
         # store the variables in the dictionary "params"
```
