### ISSUE TITLE
Duplicated imports for every question

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#121]
I've noticed in several questions the import statements are duplicated. [For example this question](https://ca.prairielearn.com/pl/course/43/question/303031/file_view/questions/stats/002.Summarizing%20Data/Q2.29_TV_Watchers/server.py)

<img width="953" alt="Screenshot 2024-08-22 at 10 24 28 PM" src="https://github.com/user-attachments/assets/ac1aadd2-fa0b-454d-af4f-5dda90493fdb">

We should probably fix this, this is likely a script issue.

**Comment by firasm** [comment]
actually what I just realized is that `def imports(data)` is wrong... so it looks like the script is adding that function definition because it's a header in the YAML section.

**Comment by Bluesy1** [comment]
This is an easy fix, I'll take care of it
