### ISSUE TITLE
Add functionality for matrix-component-unit

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#28]
PL docs: https://prairielearn.readthedocs.io/en/latest/elements/#pl-matrix-component-input-element

Sample question that would benefit:

![Image Pasted at 2022-6-14 22-07](https://user-images.githubusercontent.com/2507459/173741058-bb859ed2-832a-4ca3-93aa-1005451736f2.jpg)

Request: Paula

**Comment by Bluesy1** [comment]
Previously added in #93
