### ISSUE TITLE
Convert Backticks to `<code>` tags in parts of questions not wrapped in markdown tags

### ISSUE THREAD

**Issue by Bluesy1** [open-resources/problem_bank_scripts#35]
Currently, there is no way to add inline code blocks to portions of the answers of questions, as only question bodies and parts are wrapped in PrarieLearn's `<markdown>` tags.

This can cause a big issue for coding questions, especially for the WIP datascience problem bank where you might want a student to choose between multiple different options of code, instead of asking them to write their own code.

As such, in sections of the problem that will not be wrapped in `<markdown>` blocks, we should allow single backticks and code fences to go to `<code>` tags to allow code to be rendered in more parts of the question.

**Comment by firasm** [comment]
It looks like there's a few places I do this already in the `problem_bank_scripts.py` file. For example, here: https://github.com/open-resources/problem_bank_scripts/blob/3bcfd7d8ed9751ca325ffb0adec29c04ce59e9d7/src/problem_bank_scripts/problem_bank_scripts.py#L529
