### ISSUE TITLE
Missing functionality in `longtext` question

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#44]
Reporting a bug in the `problem_bank_scripts` code for `longtext` questions:

> when I run check.py, it doesn't seem to move the sample.html file in the template for longtext.

Christina (the student who found this bug) did a temporary workaround by changing the `checkq.py` script to the following:

```
pbs.process_question_pl(question, output_path=output_dir)
src_dir = '/'.join(question.split('/')[:-1])
dst_dir = f'{"/".join(output_dir.split("/")[:-1])}/clientFilesQuestion'
for basename in os.listdir(src_dir):
    if not basename.endswith('.md'):
        pathname = os.path.join(src_dir, basename)
        if os.path.isfile(pathname):
            if not os.path.exists(dst_dir):
                os.mkdir(dst_dir)
            shutil.copy2(pathname, dst_dir)
```

@amurph24 could you do the following:

1. Verify that applying `checkq` on longtext doesn't copy over the sample html file.
2. fix the script to ensure any assets (other than images) are copied over in the conversion to PL question? I want this to be slightly more selective (i.e. instead of excluding md, include files of specific names as specified in the config).

**Comment by amurph24** [comment]
Apologies for the delayed response.
From what I can see, the `sample.html` file is copied over for the 'q12_longtext-input/' template when `checkq` is applied to it. The original bug report mentions `check.py` (which I can't find) is this the same as `checkq`?; perhaps this was updated or debugged and already fixed at some point?
I am unable to reproduce the bug, could you link the original report or the `check.py` file?

As it stands now only files listed as an asset in the `question.md` file will be copied into the `clientFilesQuestion` dir for pl, all other files will be ignored. The `sample.html` is handled in the same way image assets are handled, we could add some filtering to only allow certain file types, or check the metadata of the files before they are moved by `checkq`? Let me know and I'll get on it.

**Comment by firasm** [comment]
Ah - hang tight, I'll see if the `sample.html` was listed as an asset.

and check is the same as checkq

**Comment by firasm** [comment]
Okay listing sample.html as an asset makes this work, so this isn't needed! 

Thanks for troubleshooting.
