### ISSUE TITLE
schema validation errors in GitHub actions

### ISSUE THREAD

**Issue by firasm** [open-resources/problem_bank_scripts#74]
See : https://github.com/open-resources/problem_bank_scripts/actions/runs/5560110838/jobs/10156848060

I checked to see if there was an update again, and there didn't seem to be one... not sure what's going on, haven't troubleshooted this in detail yet.

I'll disable the scheme check for now...

**Comment by Bluesy1** [comment]
They enabled Prettier on json files today it seems, which means the file was changed
I'd just delete the action - like you said, we'll catch it upstream where it matters, and the current version is enough for what we're using it for
If we ever need to make sure we need the most up to date version, we can bring it back again (and use a method thats a bit more foolproof than a simple diff, like comparing the files as loaded as dictionaries in python)
![image](https://github.com/open-resources/problem_bank_scripts/assets/68259537/a1a0d185-34a9-4d72-973c-b02edb97fa89)

**Comment by firasm** [comment]
sounds good, done in b00162475b5cacd895eb9b2a72ac4ab67304dc22
