### ISSUE TITLE
< doesn't render properly when in \begin{cases}

### ISSUE THREAD

**Issue by yangchristina** [open-resources/problem_bank_scripts#88]
```
$ F(x) =
\begin{cases}
  0,          x \leq {{ params.lb }}  \\\\\\\\\\\\\\\\
  ?,          {{ params.lb }} //< x &lt; {{ params.ub }} \\\\\\\\\\\\\\\\
  1,         x\geq {{ params.ub }}
\end{cases}
$
```
Renders as :
<img width="324" alt="Screenshot 2023-08-11 at 1 41 26 PM" src="https://github.com/open-resources/problem_bank_scripts/assets/69733531/3e8c66a2-0abd-40b7-b7f7-d2b76904d3c9">

**Comment by yangchristina** [comment]
Tried ``<``, ``\\<``, ``&lt;``

**Comment by Bluesy1** [comment]
Have you tried MathJax's `\lt` (and/or corresponding `\gt`) macros?
https://docs.mathjax.org/en/latest/input/tex/html.html

**Comment by yangchristina** [comment]
@Bluesy1 That works, thanks!
